# Simple Neural Network Model

This code essentially builds a simple neural network model, trains it, and evaluates its performance on a binary classification problem of predicting customer churn. You can adjust hyperparameters, add more layers, or modify the model architecture to potentially improve its performance.

# Importing Libraries:

import pandas as pd: Imports the Pandas library for data manipulation.

import numpy as np: Although not present in the code, numpy is a commonly used library for numerical operations.

from keras.models import Sequential: Imports the Sequential class from Keras, which is used to create a sequential neural network model.

from keras.layers import Dense: Imports the Dense class from Keras, which is used to create fully connected layers in the neural network.

from sklearn.model_selection import train_test_split: Imports the train_test_split function from scikit-learn to split the dataset into training and testing sets.

from sklearn.metrics import ...: Imports various metrics for evaluating the model's performance, such as precision, recall, confusion matrix, etc.

In [1]:
import pandas as pd

# Loading the Dataset:


In [2]:
dataset = pd.read_csv("Churn_Modelling.csv")

In [3]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

dataset = pd.read_csv("Churn_Modelling.csv"): Reads a CSV file named "Churn_Modelling.csv" into a Pandas DataFrame called dataset. This dataset is assumed to contain information related to customer churn.

# Data Preprocessing:

In [4]:
dataset.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [6]:
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
dataset.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

The code then proceeds to preprocess the dataset:

Extracts the target variable (y) which is "Exited."

In [8]:
y = dataset["Exited"]

Selects specific columns from the dataset to form the feature matrix (x).


In [9]:
x = dataset[  [ 'RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary' ]   ]

Converts categorical variables like "Geography," "Gender," "NumOfProducts," "HasCrCard," and "IsActiveMember" into one-hot encoded representations using pd.get_dummies.

In [10]:
geo = x["Geography"]

In [11]:
geo = pd.get_dummies(geo, drop_first=True)

In [12]:
geo

Germany  Spain
0           0      0
1           0      1
2           0      0
3           0      0
4           0      1
...       ...    ...
9995        0      0
9996        0      0
9997        0      0
9998        1      0
9999        0      0

[10000 rows x 2 columns]

In [13]:
gender = x["Gender"]

In [14]:
gender = pd.get_dummies(gender , drop_first=True)

In [15]:
NumOfProducts = x["NumOfProducts"]

In [16]:
NumOfProducts = pd.get_dummies(NumOfProducts, drop_first=True)

In [17]:
HasCrCard = x["HasCrCard"]

In [18]:
HasCrCard = pd.get_dummies(HasCrCard , drop_first=True)

In [19]:
IsActiveMember = x["IsActiveMember"]

In [20]:
IsActiveMember = pd.get_dummies(IsActiveMember , drop_first=True)

Drops the original categorical columns from x.

In [21]:
x.drop( ["RowNumber", "CustomerId", "Surname" , "Geography" , "Gender" , "NumOfProducts","HasCrCard",   "IsActiveMember" ], axis=1, inplace=True)

C:\Users\rajes\AppData\Local\Temp\ipykernel_20288\3659640665.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x.drop( ["RowNumber", "CustomerId", "Surname" , "Geography" , "Gender" , "NumOfProducts","HasCrCard",   "IsActiveMember" ], axis=1, inplace=True)


Concatenates the one-hot encoded columns with x to create the final feature matrix.

In [22]:
x = pd.concat([ x ,geo, gender, NumOfProducts,HasCrCard, IsActiveMember ], axis=1)

In [25]:
x

CreditScore  Age  Tenure    Balance  EstimatedSalary  Germany  Spain  \
0             619   42       2       0.00        101348.88        0      0   
1             608   41       1   83807.86        112542.58        0      1   
2             502   42       8  159660.80        113931.57        0      0   
3             699   39       1       0.00         93826.63        0      0   
4             850   43       2  125510.82         79084.10        0      1   
...           ...  ...     ...        ...              ...      ...    ...   
9995          771   39       5       0.00         96270.64        0      0   
9996          516   35      10   57369.61        101699.77        0      0   
9997          709   36       7       0.00         42085.58        0      0   
9998          772   42       3   75075.31         92888.52        1      0   
9999          792   28       4  130142.79         38190.78        0      0   

      Male  2  3  4  1  1  
0        0  0  0  0  1  1  
1        0  0  0  0  0  1  
2        0  0  1  0  1  0  
3        0  1  0  0  0  0  
4        0  0  0  0  1  1  
...    ... .. .. .. .. ..  
9995     1  1  0  0  1  0  
9996     1  0  0  0  1  1  
9997     0  0  0  0  0  1  
9998     1  1  0  0  1  0  
9999     0  0  0  0  1  0  

[10000 rows x 13 columns]

# Train-Test Split:

train_test_split is used to split the data into training and testing sets (x_train, x_test, y_train, y_test) with a 80-20 split ratio.

In [49]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split( x, y, test_size=0.20, random_state=20)

# Model Building:

The code creates a sequential neural network model using Keras.

In [27]:
from keras.models import Sequential # for creating model

In [28]:
model = Sequential()

In [29]:
model.get_config()

{'name': 'sequential', 'layers': []}

In [32]:
model.summary #summary of model

<bound method Model.summary of <keras.engine.sequential.Sequential object at 0x000002F15C9122B0>>

 It adds four fully connected layers (Dense) to the model. These layers use the ReLU activation function

In [30]:
from keras.layers import Dense  #for creating layers

# The first layer has 6 units and an input dimension of 13 (the number of features).

In [31]:
# layer 1
model.add(  
        Dense(
                units=6 ,  
                input_dim=13 , 
                bias_initializer="zeros",
                kernel_initializer="zeros",
                activation="relu"
        )  
)

In [33]:
model.get_config()

{'name': 'sequential',
 'layers': [{'class_name': 'InputLayer',
   'config': {'batch_input_shape': (None, 13),
    'dtype': 'float32',
    'sparse': False,
    'ragged': False,
    'name': 'dense_input'}},
  {'class_name': 'Dense',
   'config': {'name': 'dense',
    'trainable': True,
    'dtype': 'float32',
    'batch_input_shape': (None, 13),
    'units': 6,
    'activation': 'relu',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'Zeros', 'config': {}},
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'activity_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None}}]}

In [34]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 6)                 84        
                                                                 
Total params: 84
Trainable params: 84
Non-trainable params: 0
_________________________________________________________________


# The second layer has 7 units.

In [35]:
# layer 2
model.add(  
        Dense(
                units=7,#input_shap, #input shape of data (1,) means 1D array  (2,3) means 2D array with 3 columns
                bias_initializer="zeros",  #initializing bias with zero
                kernel_initializer="zeros",  #initializing weights with zero
                activation="relu"  #linear activation function for linear regression
        )  
)

In [36]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 6)                 84        
                                                                 
 dense_1 (Dense)             (None, 7)                 49        
                                                                 
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________


# The third layer has 5 units.


In [37]:
# layer 3
model.add(  
        Dense(
                units=5,
                bias_initializer="zeros",
                kernel_initializer="zeros",
                activation="relu"
        )  
)

In [38]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 6)                 84        
                                                                 
 dense_1 (Dense)             (None, 7)                 49        
                                                                 
 dense_2 (Dense)             (None, 5)                 40        
                                                                 
Total params: 173
Trainable params: 173
Non-trainable params: 0
_________________________________________________________________


# The fourth and final layer (output layer) has 1 unit and uses the sigmoid activation function, which is typical for binary classification problems.

In [39]:
# layer 4 : output layer
model.add(  
        Dense(
                units=1,
                bias_initializer="zeros",
                kernel_initializer="zeros",
                activation="sigmoid"
        )  
)

In [40]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 6)                 84        
                                                                 
 dense_1 (Dense)             (None, 7)                 49        
                                                                 
 dense_2 (Dense)             (None, 5)                 40        
                                                                 
 dense_3 (Dense)             (None, 1)                 6         
                                                                 
Total params: 179
Trainable params: 179
Non-trainable params: 0
_________________________________________________________________


In [41]:
model.get_config()

{'name': 'sequential',
 'layers': [{'class_name': 'InputLayer',
   'config': {'batch_input_shape': (None, 13),
    'dtype': 'float32',
    'sparse': False,
    'ragged': False,
    'name': 'dense_input'}},
  {'class_name': 'Dense',
   'config': {'name': 'dense',
    'trainable': True,
    'dtype': 'float32',
    'batch_input_shape': (None, 13),
    'units': 6,
    'activation': 'relu',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'Zeros', 'config': {}},
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'activity_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None}},
  {'class_name': 'Dense',
   'config': {'name': 'dense_1',
    'trainable': True,
    'dtype': 'float32',
    'units': 7,
    'activation': 'relu',
    'use_bias': True,
    'kernel_initializer': {'class_name': 'Zeros', 'config': {}},
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    '

# Model Compilation:

model.compile(loss="binary_crossentropy"): Compiles the model, specifying the binary cross-entropy loss function.

In [42]:
model.compile(loss="binary_crossentropy")

# Model Training:

model.fit(x, y): Trains the model using the entire dataset. This step is typically divided into epochs, but the code does not specify the number of epochs, so it defaults to 1 epoch.

In [43]:
model.fit(x, y)

313/313 [==============================] - 1s 1ms/step - loss: 0.6504


In [44]:
model.get_weights()

[array([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]], dtype=float32),
 array([0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0

model.fit(x, y, epochs=20): Further trains the model with 20 epochs.

In [45]:
model.fit(x, y, epochs=20)

Epoch 1/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5851
Epoch 2/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5427
Epoch 3/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5187
Epoch 4/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5093
Epoch 5/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5065
Epoch 6/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5058
Epoch 7/20
313/313 [==============================] - 0s 2ms/step - loss: 0.5056
Epoch 8/20
313/313 [==============================] - 0s 2ms/step - loss: 0.5055
Epoch 9/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5055
Epoch 10/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5055
Epoch 11/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5055
Epoch 12/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5055
Epoch 13/20
313/313 [====

In [46]:
model.fit(x, y, epochs=7)

Epoch 1/7
313/313 [==============================] - 0s 1ms/step - loss: 0.5055
Epoch 2/7
313/313 [==============================] - 0s 1ms/step - loss: 0.5055
Epoch 3/7
313/313 [==============================] - 0s 1ms/step - loss: 0.5055
Epoch 4/7
313/313 [==============================] - 0s 1ms/step - loss: 0.5055
Epoch 5/7
313/313 [==============================] - 0s 1ms/step - loss: 0.5055
Epoch 6/7
313/313 [==============================] - 0s 1ms/step - loss: 0.5055
Epoch 7/7
313/313 [==============================] - 0s 1ms/step - loss: 0.5055


In [47]:
from sklearn.metrics import precision_score, recall_score, confusion_matrix, classification_report, accuracy_score, f1_score


# Model Evaluation:
It calculates probabilities (y_pred_probs) and converts them into class predictions (y_pred) using a threshold of 0.5.

In [50]:
# Predict probabilities on the test set
y_pred_probs = model.predict(x_test)

63/63 [==============================] - 0s 919us/step


In [51]:
# Convert probabilities to class predictions
y_pred = (y_pred_probs > 0.5).astype(int)


The code then evaluates the model's performance using metrics such as accuracy, precision, recall, F1-score, confusion matrix, and classification report on the test set (x_test, y_test).

In [52]:
# Calculate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

In [53]:
# Calculate accuracy score
accuracy = accuracy_score(y_test, y_pred)

In [54]:
# Calculate precision score
precision = precision_score(y_test, y_pred)

C:\Mechanical\python anconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [55]:
# Calculate recall score
recall = recall_score(y_test, y_pred)

In [56]:
# Calculate F1 score
f1 = f1_score(y_test, y_pred)

# Printing Results:

The code prints various performance metrics, including precision, recall, F1-score, accuracy, confusion matrix, and classification report, to evaluate how well the model is performing on the test data.

In [57]:
# Print precision, recall, and F1 scores
print("Precision Score:", precision)
print("Recall Score:", recall)
print("F1 Score:", f1)

Precision Score: 0.0
Recall Score: 0.0
F1 Score: 0.0


In [58]:
# Print confusion matrix
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[1623    0]
 [ 377    0]]


In [59]:
# Print classification report
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Classification Report:
              precision    recall  f1-score   support

           0       0.81      1.00      0.90      1623
           1       0.00      0.00      0.00       377

    accuracy                           0.81      2000
   macro avg       0.41      0.50      0.45      2000
weighted avg       0.66      0.81      0.73      2000



C:\Mechanical\python anconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Mechanical\python anconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Mechanical\python anconda\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [60]:
# Calculate accuracy score (if not calculated before)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy Score:", accuracy)

Accuracy Score: 0.8115
